#!/bin/sh

echo "$2" | grep -Ei '\.xml$' >/dev/null || exit 0

pre="$(git cat-file blob "$1:$2" | md5sum)"
post="$(git cat-file blob "$1:$2" | xmllint --format - 2>/dev/null | md5sum)"

[ "$pre" != "$post" ] && exit 1

exit 0
